on:
  release:
    types: [published]

name: Publish to crates.io

steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    - uses: katyo/publish-crates@v1
      name: Publish trial-lib
      with:
          path: './trial-lib' 
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    - uses: katyo/publish-crates@v1
      name: Publish trial-runner
      with:
          path: './trial-runner' 
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
