on:
  release:
    types: [published]

name: Publish to crates.io

jobs:
  publish:
    name: Publish crates
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: katyo/publish-crates@v1
        name: Publish trial-lib
        with:
          path: './trial-lib' 
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      - uses: katyo/publish-crates@v1
        name: Publish trial-runner
        with:
          path: './trial-runner' 
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
